name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
      runs-on: ubuntu-latest
      name: Test serializer generation and serialization.
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
        - run: npm i
        - run: npm test
